Split up into fragment

diff --git a/cloud-init/lib/write_files_includes_desktop.yaml b/cloud-init/lib/write_files_includes_desktop.yaml
--- a/cloud-init/lib/write_files_includes_desktop.yaml
+++ b/cloud-init/lib/write_files_includes_desktop.yaml
@@ -1,88 +1,3 @@
-#cloud-config
-hostname: example-host
-manage_etc_hosts: true
-package_update: true
-package_upgrade: true
-package_reboot_if_required: true
-timezone: Europe/Berlin
-packages:
-  - avahi-daemon
-  # BEGIN CUSTOM PACKAGES
-  - curl
-  - dconf-editor
-  - git
-  - gnome-shell-extension-prefs
-  - gnome-tweaks
-  - make
-  - p7zip-full
-  - pipx
-  - qrencode
-  - pwgen
-  - rename
-  - tree
-  - ubuntu-advantage-tools
-  - vim
-  # Selection from normal desktop
-  - deja-dup
-  - file-roller
-  - hyphen-en-us
-  - mythes-en-us
-  - simple-scan
-  # Flatpak support
-  # - Adds Flatpak and Gnome Software to Ubuntu as well
-  # - do `pkill gnome-software` when installing by hand
-  - gnome-software-plugin-flatpak
-  # Language and additional input support
-  - hunspell-de-de
-  - hyphen-de
-  - ibus-chewing
-  - ibus-hangul
-  - ibus-libpinyin
-  - ibus-mozc
-  - mozc-utils-gui
-  - mythes-de
-  # https://wiki.debian.org/UnattendedUpgrades
-  # Unattended upgrades
-  - apt-listchanges
-  - mailutils
-  - unattended-upgrades
-  # Cosmetics
-  - breeze-cursor-theme
-  # Server
-  - btop
-  - etckeeper
-  - lm-sensors
-  - needrestart
-apt:
-  conf: |
-    Acquire {
-      Check-Date "false";
-    };
-users:
-  - name: yfn
-    gecos: Your Full Name
-    groups: users,adm,dialout,audio,netdev,video,plugdev,cdrom,games,input,gpio,spi,i2c,render,sudo
-    lock_passwd: false
-    # cspell:disable
-    passwd: $5$.abcdef$__password_hash_created_by_rpi_imager__
-    # cspell:enable
-    shell: /bin/bash
-    # cspell:disable
-    ssh_authorized_keys:
-      - "ssh-ed25519 your_key_here"
-      # cspell:enable
-      #sudo: ALL=(ALL) NOPASSWD:ALL
-runcmd:
-  - localectl set-x11-keymap "us" pc105
-  - setupcon -k --force || true
-  # Install software for Argon One case.
-  - >
-    curl "https://download.argon40.com/argon1.sh" | /bin/bash -s
-
-  # Configure dropbear for initramfs.
-  - >
-    sudo -u $( getent passwd 1000 | cut -f 1 -d ":" ) /usr/local/bin/dropbear-luks.sh
-
 write_files:
   # Suspend System to RAM when pressing the power button.
   # Without this, the setting in Gnome does not work.
@@ -95,28 +10,23 @@ write_files:
       #
       # Suspend System to RAM when pressing the power button.
       HandlePowerKey=suspend
-  # https://wiki.debian.org/UnattendedUpgrades
-  # Unattended upgrades 1/2: Install all updates automatically.
-  # Unattended upgrades 2/2: Send reports about installed updates to root mailbox.
+  # Configure override for unattended-upgrades.
   - path: "/etc/apt/apt.conf.d/52unattended-upgrades-local.conf"
     content: |
       Unattended-Upgrade::Allowed-Origins {
-              "${distro_id}:${distro_codename}";
-              "${distro_id}:${distro_codename}-security";
-              // Extended Security Maintenance; doesn't necessarily exist for
-              // every release and this system may not have it installed, but if
-              // available, the policy for updates is such that unattended-upgrades
-              // should also install from here by default.
-              "${distro_id}ESMApps:${distro_codename}-apps-security";
-              "${distro_id}ESM:${distro_codename}-infra-security";
-              // MODIFIED: Install all updates automatically.
-              "${distro_id}:${distro_codename}-updates";
-      //      "${distro_id}:${distro_codename}-updates";
-      //      "${distro_id}:${distro_codename}-proposed";
-      //      "${distro_id}:${distro_codename}-backports";
+            // Install all updates.
+            "${distro_id}:${distro_codename}-updates";
       };
 
-      // Send reports about installed updates to root mailbox.
+      Unattended-Upgrade::Origins-Pattern {
+            // Install Tailscale updates.
+            "site=pkgs.tailscale.com,component=main";
+            // Install Netdata updates.
+            "site=repo.netdata.cloud";
+            // Install all updates.
+            // "origin=*";
+      };
+
       Unattended-Upgrade::Mail "root";
   # Add ~/.local/bin to PATH, required at least for pipx.
   - path: "/etc/skel/.bashrc"
@@ -132,14 +42,61 @@ write_files:
     permissions: "0755"
     content: |
       #!/bin/bash
+      # cspell:ignore scriptslwbt ddns dfsd gext ucfq ssh-keygen PKFAIL LUKS NETDATA livewirebt ecdsa journalctl showformat iname flathub readvar luks cryptsetup tailscale netdata libexec freeipmi distro pkgs github syncthing
+
+      SSH_IMPORT_USER="livewirebt"
 
       echo -e "\nOVERVIEW\n"
 
+      echo "- FETCH SSH AUTHORIZED KEYS"
+      echo "- PRINT SSH HOST KEY FINGERPRINTS"
+      echo "- SYSTEM STATUS"
       echo "- GNOME CONFIGURATION"
       echo "- GNOME EXTENSIONS"
       echo "- CREATE SSH KEYS"
+      echo "- MISE"
+      echo "- TAILSCALE"
+      echo "- NETDATA"
+      echo "- DOTFILE DEPLOYMENT"
+      echo "- UFW FIREWALL CONFIGURATION"
 
       echo -e "\nPlease, plug in your power cable before you continue.\n"
+
+      read -rp "> Continue with FETCH SSH AUTHORIZED KEYS? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        read -ri "${SSH_IMPORT_USER}" -ep "Launchpad username: " lp_user
+        ssh-import-id-lp "${lp_user}"
+      fi
+
+      read -rp "> SSH host key FINGERPRINTS? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        for i in /etc/ssh/ssh_host_{rsa,ed25519,ecdsa}_key; do
+          sudo ssh-keygen -l -f "$i"
+        done
+      fi
+
+      read -rp "> Continue with SYSTEM STATUS? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        #systemctl --failed --no-pager
+        systemctl --failed
+        read -rp "Continue? "
+        #systemctl list-timers --no-pager
+        systemctl list-timers
+        read -rp "Continue? "
+        systemd-analyze blame
+        journalctl -p 0..err
+        read -rp "Continue? "
+        cloud-init analyze show | less
+        # shellcheck disable=SC2046
+        sudo ucfq $(dpkg-query --show --showformat='${Package} ') | less
+        sudo find "/etc/" -iname ".dpkg-" -o -iname ".ucf-"
+        sudo grep --color=always -C 3 -i -E '(^[EW]:|error|warning)' "/var/log/cloud-init-output.log" | less -R
+        sudo grep --color=always -C 1 -i -E '(^[EW]:|error|warning)' "/var/log/installer/"*".log" | less -R
+        flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
+        flatpak remotes --show-details
+        snap list
+        sudo unattended-upgrade --debug --dry-run
+      fi
 
       read -rp "> Continue with GNOME CONFIGURATION? (Y/n) " answer
       if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
@@ -171,6 +128,84 @@ write_files:
           -f "${id_file}" \
           | head -n 5 \
           | tail -n 3
+
+        echo -e "\nAdd the new public key to GitHub before you continue."
+        cat "${id_file}.pub"
+        ssh-add
+      fi
+
+      read -rp "> Continue with MISE INSTALLATION? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        cd || exit
+        curl -fsSL https://mise.run | sh
+        # shellcheck disable=SC2016
+        echo 'eval "$(~/.local/bin/mise activate bash)"' >> "${HOME}/.bashrc"
+      fi
+
+      read -rp "> Continue with TAILSCALE INSTALLATION? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        cd || exit
+        curl -fsSL https://tailscale.com/install.sh | sh
+        sudo tailscale up --qr
+      fi
+
+      read -rp "> Continue with NETDATA INSTALLATION? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        #cd; curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh --nightly-channel
+        cd || exit
+        curl https://get.netdata.cloud/kickstart.sh > /tmp/netdata-kickstart.sh && sh /tmp/netdata-kickstart.sh
+        sudo /usr/libexec/netdata/netdata-updater.sh --enable-auto-updates
+        sudo apt install -y netdata-plugin-freeipmi
+      fi
+
+      # Deploy dotfiles part 3 without deploy keys.
+      # Create SSH key before to access all repositories.
+      read -rp "> Continue with DOTFILE DEPLOYMENT? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        cd || exit
+        curl -LO scriptslwbt.ddns.me/dfsd3-install.sh && bash dfsd3-install.sh
+      fi
+
+      read -rp "> Continue with UFW FIREWALL CONFIGURATION? (Y/n) " answer
+      if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+        # Check if UFW is active.
+        sudo ufw status numbered
+
+        # UFW app profile list.
+        sudo ufw app list
+
+        # Enable app profiles in UFW.
+        # TODO: Newline or zero delimiter for services.
+        for service in $(sudo ufw app list | tail -n +2 | sed -e 's/^  //g'); do
+          [[ "${service}" == "syncthing-gui" ]] && break
+
+          read -rp "> Allow '${service}' in UFW? (Y/n) " answer
+          if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+
+            sudo ufw allow "${service}"
+          fi
+        done
+
+        #for service in $(sudo ufw app list | tail -n +2 | sed -e 's/^  //g'); do
+        #  # TODO: If list contains, else report.
+        #  [[ "${service}" != "syncthing-gui" ]] && break
+        #  # ...
+        #done
+
+        app_profile="syncthing-gui"
+        for ipr in "100.0.0.0/8" "fd7a:115c:a1e0::/48"; do
+          # TODO: If list contains, else report.
+
+          read -rp "> Allow IP range '${ipr}' in UFW for ${app_profile}? (Y/n) " answer
+          if [[ ! "${answer}" =~ (^[Nn]|^[Nn]"o") ]]; then
+
+            sudo ufw allow from "${ipr}" to any app "${app_profile}"
+          fi
+        done
+
+        sudo ufw enable
+
+        sudo ufw status numbered
       fi
 
       rm -v "$HOME/post_install_setup.sh"
@@ -292,6 +327,3 @@ write_files:
           <options>zoom</options>
         </wallpaper>
       </wallpapers>
-power_state:
-  delay: now
-  mode: reboot
